{{ if .Values.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    openshift.io/display-name: "MinIO S3 Storage"
    argocd.argoproj.io/sync-wave: "0"
{{ end }}
