---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.security.secretName }}
  namespace: {{ .Values.namespace }}
type: Opqaue
stringData:
  MINIO_ROOT_USER: {{ .Values.security.username }}
  MINIO_ROOT_PASSWORD: {{ .Values.security.password }}
