---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  volumeMode: {{ .Values.storage.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
